In [4]:
from tensorflow.keras import Sequential, layers
import tensorflow as tf

# Basically, it will look like a sequence of layers 
model = Sequential()

In [5]:
X = tf.ones((3,3))
X

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [6]:
X.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)